version: "3.0"

services:
    api:
        container_name: git_verify
        build: .
        restart: always
        ports:
            - "${HTTP_PORT}:80"
        environment:
            - "GITEA_URL=${GITEA_URL}"
            - "GITEA_TOKEN=${GITEA_TOKEN}"
